### ISSUE TITLE
Where am I doing wrong.

### ISSUE THREAD

**Issue by fb11** [Rizer0/Blind-Bash#2]
<img width="618" alt="bash" src="https://user-images.githubusercontent.com/11415252/43996622-766153f0-9dcf-11e8-859d-be3d95c98637.png">

**Comment by E3V3A** [comment]
@fb11 You need to put your script in the `./in/` subdirectory. Then it seem like you will find the result in the `out` sub...

**Comment by Nullbyte0x** [comment]
your file should be in "/in/" subdirectory
and your result gonna be in "/out/" subdirectory
